window.services = [
  {
    name: "Claude",
    url: "https://claude.ai",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Anthropic의 장문 분석, 글쓰기, 코딩에 강한 AI 어시스턴트.",
    tags: ["대화", "문서", "코딩"],
    tone: "#6f5a48",
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Google 생태계와 연결되는 멀티모달 AI 어시스턴트.",
    tags: ["Google", "멀티모달", "생산성"],
    tone: "#4285f4",
  },
  {
    name: "Grok",
    url: "https://grok.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "xAI의 챗봇 서비스로 실시간 정보 탐색과 대화형 답변에 초점.",
    tags: ["xAI", "실시간", "챗봇"],
    tone: "#111827",
  },
  {
    name: "Genspark",
    url: "https://www.genspark.ai",
    category: "플랫폼/리서치",
    subcategory: "검색/리서치",
    summary: "AI 검색, 리서치, 자동 페이지 생성형 결과를 제공하는 탐색 도구.",
    tags: ["검색", "리서치", "요약"],
    tone: "#f97316",
  },
  {
    name: "Whisk",
    url: "https://labs.google/fx/tools/whisk",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "Google Labs의 이미지 기반 프롬프트와 시각 실험 도구.",
    tags: ["Google Labs", "이미지", "실험"],
    tone: "#0f8f72",
  },
  {
    name: "Suno",
    url: "https://suno.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "텍스트 프롬프트로 보컬과 반주가 포함된 음악을 생성하는 서비스.",
    tags: ["음악", "보컬", "작곡"],
    tone: "#d94c42",
  },
  {
    name: "Lovable",
    url: "https://lovable.dev",
    category: "개발/코딩",
    subcategory: "앱/웹 빌더",
    summary: "자연어로 웹앱을 빠르게 설계하고 구현하는 AI 앱 빌더.",
    tags: ["웹앱", "프로토타입", "개발"],
    tone: "#e11d48",
  },
  {
    name: "v0",
    url: "https://v0.dev",
    category: "개발/코딩",
    subcategory: "앱/웹 빌더",
    summary: "Vercel의 UI 생성 도구로 React 기반 화면을 빠르게 제작.",
    tags: ["UI", "React", "Vercel"],
    tone: "#000000",
  },
  {
    name: "Hugging Face",
    url: "https://huggingface.co",
    category: "플랫폼/리서치",
    subcategory: "모델 허브",
    summary: "오픈 모델, 데이터셋, 데모 앱을 찾고 배포하는 AI 커뮤니티 허브.",
    tags: ["모델", "데이터셋", "오픈소스"],
    tone: "#ffb000",
  },
  {
    name: "GitHub",
    url: "https://github.com",
    category: "Git/저장소",
    subcategory: "코드/저장소",
    summary: "코드 저장소, 협업, GitHub Copilot 기반 개발 워크플로의 중심.",
    tags: ["Git", "협업", "Copilot"],
    tone: "#24292f",
  },
  {
    name: "Cursor",
    url: "https://cursor.com",
    category: "개발/코딩",
    subcategory: "AI 코드 에디터",
    summary: "프로젝트 전체 문맥을 바탕으로 코드 작성과 수정에 특화된 AI 에디터.",
    tags: ["에디터", "AI 코딩", "리팩터링"],
    tone: "#111827",
  },
  {
    name: "Windsurf",
    url: "https://windsurf.com",
    category: "개발/코딩",
    subcategory: "AI 코드 에디터",
    summary: "Cascade 기반 에이전트 코딩 흐름을 제공하는 AI 개발 환경.",
    tags: ["에디터", "에이전트", "개발"],
    tone: "#06b6d4",
  },
  {
    name: "Replit",
    url: "https://replit.com",
    category: "개발/코딩",
    subcategory: "앱/웹 빌더",
    summary: "브라우저에서 코딩, AI 생성, 실행, 배포까지 이어지는 개발 플랫폼.",
    tags: ["IDE", "실행", "배포"],
    tone: "#f26207",
  },
  {
    name: "StackBlitz",
    url: "https://stackblitz.com",
    category: "개발/코딩",
    subcategory: "앱/웹 빌더",
    summary: "웹 기반 프론트엔드 개발과 빠른 프로토타이핑에 유용한 IDE.",
    tags: ["웹 IDE", "프론트엔드", "프로토타입"],
    tone: "#1374ef",
  },
  {
    name: "Vercel",
    url: "https://vercel.com",
    category: "배포/호스팅",
    subcategory: "배포/호스팅",
    summary: "Next.js와 프론트엔드 앱 배포에 강한 글로벌 호스팅 플랫폼.",
    tags: ["배포", "프론트엔드", "Next.js"],
    tone: "#000000",
  },
  {
    name: "Netlify",
    url: "https://www.netlify.com",
    category: "배포/호스팅",
    subcategory: "배포/호스팅",
    summary: "정적 사이트와 JAMstack 프로젝트를 빠르게 배포하는 플랫폼.",
    tags: ["배포", "정적 사이트", "JAMstack"],
    tone: "#00ad9f",
  },
  {
    name: "Cloudflare Pages",
    url: "https://pages.cloudflare.com",
    category: "배포/호스팅",
    subcategory: "배포/호스팅",
    summary: "Cloudflare 네트워크 위에서 프론트엔드 사이트를 배포하는 서비스.",
    tags: ["CDN", "배포", "프론트엔드"],
    tone: "#f38020",
  },
  {
    name: "Railway",
    url: "https://railway.app",
    category: "배포/호스팅",
    subcategory: "배포/호스팅",
    summary: "웹앱, API, 데이터베이스를 간단히 띄우는 풀스택 배포 플랫폼.",
    tags: ["풀스택", "API", "DB"],
    tone: "#7957d5",
  },
  {
    name: "Render",
    url: "https://render.com",
    category: "배포/호스팅",
    subcategory: "배포/호스팅",
    summary: "웹 서비스, 백그라운드 작업, 정적 사이트를 운영하는 호스팅 서비스.",
    tags: ["웹서비스", "서버", "배포"],
    tone: "#46e3b7",
  },
  {
    name: "GitLab",
    url: "https://gitlab.com",
    category: "Git/저장소",
    subcategory: "코드/저장소",
    summary: "저장소, 이슈, CI/CD를 함께 제공하는 개발 협업 플랫폼.",
    tags: ["Git", "CI/CD", "협업"],
    tone: "#fc6d26",
  },
  {
    name: "Bitbucket",
    url: "https://bitbucket.org",
    category: "Git/저장소",
    subcategory: "코드/저장소",
    summary: "Atlassian 생태계와 연결되는 Git 저장소 및 협업 서비스.",
    tags: ["Git", "Atlassian", "협업"],
    tone: "#0052cc",
  },
  {
    name: "Supabase",
    url: "https://supabase.com",
    category: "데이터/백엔드",
    subcategory: "DB/백엔드",
    summary: "Postgres 기반 DB, 인증, 스토리지, Edge Functions를 제공하는 백엔드 플랫폼.",
    tags: ["Postgres", "Auth", "Backend"],
    tone: "#3ecf8e",
  },
  {
    name: "Firebase",
    url: "https://firebase.google.com",
    category: "데이터/백엔드",
    subcategory: "DB/백엔드",
    summary: "Google의 앱 백엔드 플랫폼으로 인증, DB, 호스팅, 분석을 제공.",
    tags: ["Google", "Auth", "DB"],
    tone: "#ffca28",
  },
  {
    name: "Neon",
    url: "https://neon.tech",
    category: "데이터/백엔드",
    subcategory: "DB/백엔드",
    summary: "서버리스 Postgres와 브랜치 기반 데이터베이스 워크플로를 제공.",
    tags: ["Postgres", "Serverless", "DB"],
    tone: "#00e599",
  },
  {
    name: "Postman",
    url: "https://www.postman.com",
    category: "개발/코딩",
    subcategory: "API/테스트",
    summary: "API 요청, 문서화, 테스트, 협업을 위한 대표적인 개발 도구.",
    tags: ["API", "테스트", "문서"],
    tone: "#ff6c37",
  },
  {
    name: "ChatGPT",
    url: "https://chatgpt.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "OpenAI의 대표 AI 어시스턴트로 글쓰기, 분석, 이미지, 코드 작업에 활용.",
    tags: ["OpenAI", "대화", "멀티모달"],
    tone: "#10a37f",
  },
  {
    name: "Perplexity",
    url: "https://www.perplexity.ai",
    category: "플랫폼/리서치",
    subcategory: "검색/리서치",
    summary: "출처 기반 답변과 웹 검색에 강한 AI 리서치 서비스.",
    tags: ["검색", "출처", "리서치"],
    tone: "#1f9ea7",
  },
  {
    name: "Midjourney",
    url: "https://www.midjourney.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "고품질 스타일 이미지 생성으로 널리 쓰이는 크리에이티브 AI 도구.",
    tags: ["이미지", "아트", "디자인"],
    tone: "#5b5f97",
  },
  {
    name: "Runway",
    url: "https://runwayml.com",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "AI 영상 생성, 편집, 모션 작업을 지원하는 크리에이티브 플랫폼.",
    tags: ["영상", "편집", "크리에이티브"],
    tone: "#0b1f3a",
  },
  {
    name: "Microsoft Copilot",
    url: "https://copilot.microsoft.com",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "Microsoft 365와 웹 작업에 연결되는 생산성 중심 AI 어시스턴트.",
    tags: ["Microsoft", "업무", "문서"],
    tone: "#0078d4",
  },
  {
    name: "Canva AI",
    url: "https://www.canva.com/ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "디자인 제작 과정에 이미지 생성, 편집, 문구 작성 AI를 통합.",
    tags: ["디자인", "마케팅", "이미지"],
    tone: "#00c4cc",
  },
  {
    name: "Notion AI",
    url: "https://www.notion.so/product/ai",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "노트, 문서, 지식관리 안에서 요약과 작성 보조를 제공.",
    tags: ["노트", "문서", "지식관리"],
    tone: "#111111",
  },
  {
    name: "DeepSeek",
    url: "https://chat.deepseek.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "추론과 코딩 작업에 많이 활용되는 AI 챗 서비스.",
    tags: ["추론", "코딩", "대화"],
    tone: "#2f6fed",
  },
  {
    name: "Kimi",
    url: "https://www.kimi.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "긴 문서 읽기, 요약, 분석에 강한 대화형 AI 어시스턴트.",
    tags: ["장문", "문서", "요약"],
    tone: "#5b7cfa",
  },
  {
    name: "Le Chat",
    url: "https://chat.mistral.ai",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Mistral AI의 공식 챗봇으로 빠른 응답과 실무형 대화에 활용.",
    tags: ["Mistral", "대화", "업무"],
    tone: "#ff7000",
  },
  {
    name: "ElevenLabs",
    url: "https://elevenlabs.io",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "자연스러운 음성 합성, 더빙, 보이스 클로닝에 특화된 서비스.",
    tags: ["TTS", "더빙", "음성"],
    tone: "#6c4cff",
  },
  {
    name: "Ideogram",
    url: "https://ideogram.ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "텍스트가 포함된 포스터, 로고, 시각 디자인 생성에 강한 이미지 AI.",
    tags: ["이미지", "타이포", "로고"],
    tone: "#c026d3",
  },
  {
    name: "Mobbin",
    url: "https://mobbin.com",
    category: "디자인/UX",
    subcategory: "디자인 레퍼런스",
    summary: "실제 모바일 앱과 웹 서비스의 화면, UI 패턴, 사용자 플로우를 찾는 레퍼런스 라이브러리.",
    tags: ["UI 패턴", "앱 화면", "플로우"],
    tone: "#111827",
  },
  {
    name: "Awwwards",
    url: "https://www.awwwards.com",
    category: "디자인/UX",
    subcategory: "디자인 레퍼런스",
    summary: "수준 높은 웹디자인, 인터랙션, 랜딩페이지 사례를 탐색하는 글로벌 웹 어워드 플랫폼.",
    tags: ["웹디자인", "인터랙션", "레퍼런스"],
    tone: "#121212",
  },
  {
    name: "Figma Community",
    url: "https://www.figma.com/community",
    category: "디자인/UX",
    subcategory: "디자인 시스템",
    summary: "UI 키트, 디자인 시스템, 템플릿, 플러그인을 찾아 바로 복제해 쓰는 Figma 자료실.",
    tags: ["UI Kit", "템플릿", "Figma"],
    tone: "#a259ff",
  },
  {
    name: "shadcn/ui",
    url: "https://ui.shadcn.com",
    category: "디자인/UX",
    subcategory: "디자인 시스템",
    summary: "복사해 프로젝트에 소유권을 두고 커스터마이즈하는 React 컴포넌트 기반 디자인 시스템.",
    tags: ["React", "컴포넌트", "Tailwind"],
    tone: "#09090b",
  },
  {
    name: "Relume",
    url: "https://www.relume.io",
    category: "디자인/UX",
    subcategory: "디자인 시스템",
    summary: "AI로 사이트맵, 와이어프레임, 스타일가이드를 빠르게 만들고 Figma나 React로 이어주는 도구.",
    tags: ["와이어프레임", "사이트맵", "AI"],
    tone: "#2563eb",
  },
  {
    name: "Lucide",
    url: "https://lucide.dev",
    category: "디자인/UX",
    subcategory: "아이콘/에셋",
    summary: "웹앱과 대시보드에 쓰기 좋은 일관된 선형 오픈소스 아이콘 세트.",
    tags: ["아이콘", "SVG", "오픈소스"],
    tone: "#f56565",
  },
  {
    name: "Realtime Colors",
    url: "https://www.realtimecolors.com",
    category: "디자인/UX",
    subcategory: "색상/폰트",
    summary: "텍스트, 배경, 강조색 조합을 실제 UI 화면에서 바로 확인하는 컬러 팔레트 도구.",
    tags: ["컬러", "팔레트", "접근성"],
    tone: "#7c3aed",
  },
  {
    name: "Google Fonts",
    url: "https://fonts.google.com",
    category: "디자인/UX",
    subcategory: "색상/폰트",
    summary: "웹 프로젝트에 바로 적용하기 좋은 무료 폰트를 검색하고 조합하는 공식 폰트 라이브러리.",
    tags: ["폰트", "타이포", "웹폰트"],
    tone: "#4285f4",
  },
  {
    name: "Unsplash",
    url: "https://unsplash.com",
    category: "디자인/UX",
    subcategory: "아이콘/에셋",
    summary: "랜딩페이지, 블로그, 목업에 사용할 고품질 사진을 찾는 이미지 라이브러리.",
    tags: ["사진", "이미지", "비주얼"],
    tone: "#000000",
  },
  {
    name: "Spline",
    url: "https://spline.design",
    category: "디자인/UX",
    subcategory: "아이콘/에셋",
    summary: "웹에서 사용할 3D 오브젝트와 인터랙티브 씬을 제작하는 디자인 도구.",
    tags: ["3D", "인터랙션", "웹"],
    tone: "#7057ff",
  },
  {
    name: "Freebuff",
    url: "https://freebuff.com",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "구독 없이 설치해 쓰는 무료 터미널 기반 AI 코딩 에이전트.",
    tags: ["CLI", "무료", "서브에이전트"],
    tone: "#111827",
  },
  {
    name: "Codebuff",
    url: "https://www.codebuff.com",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "자연어 지시로 코드베이스를 이해하고 여러 에이전트가 협업해 코드를 수정하는 오픈소스 코딩 어시스턴트.",
    tags: ["오픈소스", "멀티에이전트", "CLI"],
    tone: "#2563eb",
  },
  {
    name: "Claude Code",
    url: "https://code.claude.com",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "코드베이스를 읽고 파일 수정, 명령 실행, Git 작업까지 처리하는 Anthropic의 에이전트형 코딩 도구.",
    tags: ["Claude", "CLI", "에이전트"],
    tone: "#6f5a48",
  },
  {
    name: "OpenAI Codex",
    url: "https://developers.openai.com/codex",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "코드 생성, 수정, 자동화 작업을 위한 OpenAI의 소프트웨어 엔지니어링 에이전트 제품군.",
    tags: ["OpenAI", "Codex", "자동화"],
    tone: "#10a37f",
  },
  {
    name: "Gemini CLI",
    url: "https://github.com/google-gemini/gemini-cli",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "Gemini를 터미널에서 사용하는 Google의 오픈소스 AI 에이전트 CLI.",
    tags: ["Google", "Gemini", "CLI"],
    tone: "#4285f4",
  },
  {
    name: "OpenCode",
    url: "https://opencode.ai",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "터미널 중심으로 동작하는 오픈소스 AI 코딩 에이전트.",
    tags: ["오픈소스", "CLI", "코딩"],
    tone: "#111827",
  },
  {
    name: "Aider",
    url: "https://aider.chat",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "Git 저장소 안에서 대화하며 코드를 수정하고 커밋 흐름까지 돕는 터미널 AI 페어 프로그래밍 도구.",
    tags: ["터미널", "Git", "페어코딩"],
    tone: "#16a34a",
  },
  {
    name: "Cline",
    url: "https://cline.bot",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "VS Code 안에서 파일 수정, 명령 실행, 브라우저 작업까지 처리하는 오픈소스 AI 코딩 에이전트.",
    tags: ["VS Code", "오픈소스", "브라우저"],
    tone: "#7c3aed",
  },
  {
    name: "Continue",
    url: "https://www.continue.dev",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "팀이 자체 모델과 규칙을 연결해 코드 자동완성, 채팅, 에이전트 흐름을 구성하는 오픈소스 AI 개발 플랫폼.",
    tags: ["오픈소스", "팀", "커스텀"],
    tone: "#0f766e",
  },
  {
    name: "Amp",
    url: "https://ampcode.com",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "터미널, 웹, 모바일에서 이어서 사용할 수 있는 Sourcegraph 계열의 에이전트형 코딩 도구.",
    tags: ["CLI", "원격제어", "에이전트"],
    tone: "#f97316",
  },
  {
    name: "Devin",
    url: "https://devin.ai",
    category: "개발/코딩",
    subcategory: "AI 코딩 에이전트",
    summary: "코드 마이그레이션, 버그 수정, PR 리뷰 같은 엔지니어링 작업을 위임하는 자율형 AI 소프트웨어 엔지니어.",
    tags: ["자율 에이전트", "PR 리뷰", "마이그레이션"],
    tone: "#111827",
  },
  {
    name: "Google AI Studio",
    url: "https://aistudio.google.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "Gemini 모델을 실험하고 프롬프트, 멀티모달 입력, API 코드 생성을 테스트하는 Google의 AI 개발 콘솔.",
    tags: ["Gemini", "Playground", "API"],
    tone: "#4285f4",
  },
  {
    name: "OpenAI Playground",
    url: "https://platform.openai.com/playground",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "OpenAI 모델의 프롬프트, 파라미터, 응답 형식을 실험하고 API 구현으로 이어가는 개발자 플레이그라운드.",
    tags: ["OpenAI", "Playground", "API"],
    tone: "#10a37f",
  },
  {
    name: "Claude Platform",
    url: "https://platform.claude.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "Claude 모델 API, 프롬프트 테스트, 사용량 관리, 개발자 문서로 이어지는 Anthropic 개발 플랫폼.",
    tags: ["Claude", "Anthropic", "API"],
    tone: "#6f5a48",
  },
  {
    name: "Mistral La Plateforme",
    url: "https://console.mistral.ai",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "Mistral 모델을 테스트하고 API 키, 모델 설정, 개발자 콘솔을 관리하는 공식 플랫폼.",
    tags: ["Mistral", "모델", "API"],
    tone: "#ff7000",
  },
  {
    name: "GroqCloud",
    url: "https://console.groq.com/playground",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "고속 추론 모델을 Playground에서 테스트하고 API 키와 대시보드를 관리하는 Groq 개발자 콘솔.",
    tags: ["Groq", "추론", "Playground"],
    tone: "#f55036",
  },
  {
    name: "Replicate",
    url: "https://replicate.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "이미지, 영상, 음성, LLM 모델을 실행하고 API로 연결하며 커스텀 모델 배포까지 지원하는 플랫폼.",
    tags: ["모델 실행", "API", "배포"],
    tone: "#111827",
  },
  {
    name: "OpenRouter",
    url: "https://openrouter.ai",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "여러 LLM 제공사의 모델을 하나의 API 라우터로 비교하고 연결하는 모델 게이트웨이.",
    tags: ["LLM", "라우터", "API"],
    tone: "#7c3aed",
  },
  {
    name: "Together AI",
    url: "https://api.together.ai",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "오픈 모델과 상용 모델을 API로 실행하고 파인튜닝, 추론, 배포 흐름을 제공하는 AI 클라우드 플랫폼.",
    tags: ["오픈모델", "추론", "API"],
    tone: "#ec4899",
  },
  {
    name: "Fireworks AI",
    url: "https://fireworks.ai",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "빠른 추론 API, 모델 서빙, 파인튜닝을 제공하는 개발자 중심 AI 인프라 플랫폼.",
    tags: ["추론", "서빙", "파인튜닝"],
    tone: "#ef4444",
  },
  {
    name: "Meta AI",
    url: "https://www.meta.ai",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Meta의 무료 AI. Llama 3 기반, Instagram·WhatsApp·Facebook 연동",
    tags: ["대화","AI","챗봇"],
    tone: "#0866ff",
  },
  {
    name: "Character.AI",
    url: "https://character.ai",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "AI 캐릭터와 대화하는 플랫폼. 유명인·애니 캐릭터·나만의 AI 생성",
    tags: ["대화","AI","챗봇"],
    tone: "#7c3aed",
  },
  {
    name: "Poe",
    url: "https://poe.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Quora의 멀티 AI 챗 플랫폼. Claude·GPT·Gemini 등 여러 AI를 한 곳에서",
    tags: ["대화","AI","챗봇"],
    tone: "#6366f1",
  },
  {
    name: "Qwen",
    url: "https://chat.qwenlm.ai",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Alibaba의 통이치엔원(通義千問) AI. 멀티모달 지원, 코딩·수학 강점",
    tags: ["대화","AI","챗봇"],
    tone: "#7c3aed",
  },
  {
    name: "Doubao",
    url: "https://www.doubao.com",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "ByteDance(TikTok 모회사)의 AI 챗봇. 빠른 응답 속도와 멀티모달 기능",
    tags: ["대화","AI","챗봇"],
    tone: "#1d4ed8",
  },
  {
    name: "Pi",
    url: "https://pi.ai",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "Inflection AI의 대화형 AI. 공감·감성 중심 대화 특화, 개인 코치 역할",
    tags: ["대화","AI","챗봇"],
    tone: "#ec4899",
  },
  {
    name: "HuggingChat",
    url: "https://huggingface.co/chat",
    category: "AI 챗봇",
    subcategory: "대화형 AI",
    summary: "HuggingFace의 무료 오픈소스 챗봇 허브. Llama·Mistral·Gemma 등 다양한 모델 선택",
    tags: ["대화","AI","챗봇"],
    tone: "#ff9a00",
  },
  {
    name: "You.com",
    url: "https://you.com",
    category: "플랫폼/리서치",
    subcategory: "검색/리서치",
    summary: "개인화 AI 검색 엔진. Code·Write·Research 등 다양한 AI 모드 지원",
    tags: ["검색","리서치","요약"],
    tone: "#6366f1",
  },
  {
    name: "Phind",
    url: "https://www.phind.com",
    category: "플랫폼/리서치",
    subcategory: "검색/리서치",
    summary: "개발자 특화 AI 코드 검색. 기술 문서·Stack Overflow 통합 검색",
    tags: ["검색","리서치","요약"],
    tone: "#8b5cf6",
  },
  {
    name: "Consensus",
    url: "https://consensus.app",
    category: "플랫폼/리서치",
    subcategory: "검색/리서치",
    summary: "학술 논문 기반 AI 검색. 과학적 근거 기반 답변 제공",
    tags: ["검색","리서치","요약"],
    tone: "#0ea5e9",
  },
  {
    name: "Liner",
    url: "https://getliner.com",
    category: "플랫폼/리서치",
    subcategory: "검색/리서치",
    summary: "AI 기반 웹 리서치 & 하이라이트 도구. 논문·뉴스 요약 특화",
    tags: ["검색","리서치","요약"],
    tone: "#ef4444",
  },
  {
    name: "뤼튼 (Wrtn)",
    url: "https://wrtn.ai",
    category: "AI 챗봇",
    subcategory: "한국 AI 서비스",
    summary: "한국 대표 무료 AI 글쓰기 어시스턴트. GPT-4·Claude 무제한 무료 사용",
    tags: ["한국어","AI","국내"],
    tone: "#2563eb",
  },
  {
    name: "네이버 클로바X",
    url: "https://clova-x.naver.com",
    category: "AI 챗봇",
    subcategory: "한국 AI 서비스",
    summary: "네이버의 AI 어시스턴트 클로바X. 한국어 특화 대화 & 검색 연동",
    tags: ["한국어","AI","국내"],
    tone: "#03c75a",
  },
  {
    name: "카카오 AI",
    url: "https://kakaoenterprise.com",
    category: "AI 챗봇",
    subcategory: "한국 AI 서비스",
    summary: "카카오의 AI 플랫폼. KoGPT 기반 한국어 특화 AI 서비스",
    tags: ["한국어","AI","국내"],
    tone: "#fee500",
  },
  {
    name: "SKT A.",
    url: "https://www.sktelekom.com/ai",
    category: "AI 챗봇",
    subcategory: "한국 AI 서비스",
    summary: "SKT의 AI 어시스턴트. 국내 이동통신사 기반 AI 서비스",
    tags: ["한국어","AI","국내"],
    tone: "#e20000",
  },
  {
    name: "DALL-E 3",
    url: "https://labs.openai.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "OpenAI의 텍스트→이미지 AI. ChatGPT에서 직접 생성 가능, 높은 정확도",
    tags: ["이미지","생성","디자인"],
    tone: "#10a37f",
  },
  {
    name: "Stable Diffusion",
    url: "https://stability.ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "오픈소스 이미지 생성 AI 선구자. 로컬 설치 & 커스터마이징 무한 가능",
    tags: ["이미지","생성","디자인"],
    tone: "#7c3aed",
  },
  {
    name: "Adobe Firefly",
    url: "https://firefly.adobe.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "Adobe의 생성형 AI. 상업적으로 안전한 이미지 생성, CC 앱 통합",
    tags: ["이미지","생성","디자인"],
    tone: "#e34500",
  },
  {
    name: "Playground",
    url: "https://playground.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "무료 AI 이미지 생성 & 편집 플랫폼. 직관적 UI로 초보자 친화적",
    tags: ["이미지","생성","디자인"],
    tone: "#0ea5e9",
  },
  {
    name: "Leonardo AI",
    url: "https://leonardo.ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "게임·디자인 특화 AI 이미지. 캐릭터·에셋·3D 스타일 이미지 강점",
    tags: ["이미지","생성","디자인"],
    tone: "#f59e0b",
  },
  {
    name: "Krea AI",
    url: "https://www.krea.ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "실시간 AI 이미지 생성 & 향상. 스케치→이미지 실시간 변환 기능 독보적",
    tags: ["이미지","생성","디자인"],
    tone: "#ec4899",
  },
  {
    name: "Flux",
    url: "https://flux1.ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "Black Forest Labs의 Flux 모델. 최신 오픈소스 이미지 생성 최강자",
    tags: ["이미지","생성","디자인"],
    tone: "#8b5cf6",
  },
  {
    name: "Pika",
    url: "https://pika.art",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "이미지·텍스트→비디오 변환 AI. 직관적인 UI로 빠른 영상 제작 가능",
    tags: ["영상","생성","콘텐츠"],
    tone: "#ec4899",
  },
  {
    name: "Kling AI",
    url: "https://klingai.com",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "쾌수 AI의 고품질 비디오 생성. 사실적인 인물 동작 표현 우수",
    tags: ["영상","생성","콘텐츠"],
    tone: "#3b82f6",
  },
  {
    name: "Sora",
    url: "https://sora.com",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "OpenAI의 텍스트→비디오 AI. 최대 1분 고품질 영상 생성",
    tags: ["영상","생성","콘텐츠"],
    tone: "#374151",
  },
  {
    name: "Luma Dream",
    url: "https://lumalabs.ai/dream-machine",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "Luma AI의 Dream Machine. 사실적이고 부드러운 영상 생성 특화",
    tags: ["영상","생성","콘텐츠"],
    tone: "#f97316",
  },
  {
    name: "Hailuo AI",
    url: "https://hailuoai.video",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "MiniMax의 AI 비디오. 초현실적 영상 품질, 한국어 지원",
    tags: ["영상","생성","콘텐츠"],
    tone: "#8b5cf6",
  },
  {
    name: "Synthesia",
    url: "https://www.synthesia.io",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "AI 아바타로 전문 교육·마케팅 영상 제작. 130개 언어 AI 더빙 지원",
    tags: ["영상","생성","콘텐츠"],
    tone: "#0ea5e9",
  },
  {
    name: "InVideo AI",
    url: "https://invideo.io",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "텍스트 입력만으로 완성된 영상을 자동 생성. SNS 콘텐츠 제작에 최적",
    tags: ["영상","생성","콘텐츠"],
    tone: "#f59e0b",
  },
  {
    name: "D-ID",
    url: "https://www.d-id.com",
    category: "이미지/영상",
    subcategory: "영상 생성",
    summary: "사진→말하는 AI 아바타 변환. 교육 콘텐츠·프레젠테이션 영상 활용",
    tags: ["영상","생성","콘텐츠"],
    tone: "#6366f1",
  },
  {
    name: "CapCut",
    url: "https://www.capcut.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "AI 기반 영상·이미지 편집 앱. 자동 자막·배경 제거·AI 필터 탑재",
    tags: ["이미지","편집","디자인"],
    tone: "#1a1a1a",
  },
  {
    name: "Magnific AI",
    url: "https://magnific.ai",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "AI 이미지 초고해상도 업스케일러. 저화질 이미지를 8K 화질로 향상",
    tags: ["이미지","편집","디자인"],
    tone: "#7c3aed",
  },
  {
    name: "Remove.bg",
    url: "https://www.remove.bg",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "AI 자동 배경 제거 도구. 클릭 한 번으로 배경 즉시 삭제",
    tags: ["이미지","편집","디자인"],
    tone: "#ef4444",
  },
  {
    name: "Clipdrop",
    url: "https://clipdrop.co",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "Stability AI의 이미지 편집 도구 모음. 지우기·교체·향상 기능 통합",
    tags: ["이미지","편집","디자인"],
    tone: "#7c3aed",
  },
  {
    name: "Adobe Express",
    url: "https://www.adobe.com/kr/express",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "Adobe의 빠른 AI 이미지 편집 & 소셜 미디어 콘텐츠 제작 도구",
    tags: ["이미지","편집","디자인"],
    tone: "#e34500",
  },
  {
    name: "Topaz Labs",
    url: "https://www.topazlabs.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "AI 사진·영상 화질 향상 전문 도구. 노이즈 제거·선명화 업계 최강",
    tags: ["이미지","편집","디자인"],
    tone: "#0ea5e9",
  },
  {
    name: "Microsoft Designer",
    url: "https://designer.microsoft.com",
    category: "이미지/영상",
    subcategory: "이미지 생성/편집",
    summary: "Microsoft Copilot 기반 AI 디자인 도구. 텍스트 입력만으로 소셜 미디어 콘텐츠·이미지 자동 생성",
    tags: ["이미지","편집","디자인"],
    tone: "#0078d4",
  },
  {
    name: "wwit.design",
    url: "https://wwit.design",
    category: "디자인/UX",
    subcategory: "디자인 레퍼런스",
    summary: "실제 서비스 모바일 UI 캡처 레퍼런스 사이트. 국내외 앱·웹 디자인 트렌드 모음",
    tags: ["UI","레퍼런스","디자인"],
    tone: "#0f172a",
  },
  {
    name: "Dribbble",
    url: "https://dribbble.com",
    category: "디자인/UX",
    subcategory: "디자인 레퍼런스",
    summary: "UI/UX 디자이너 포트폴리오 & 인스피레이션 커뮤니티. 전 세계 1위 디자인 플랫폼",
    tags: ["UI","레퍼런스","디자인"],
    tone: "#ea4c89",
  },
  {
    name: "Behance",
    url: "https://www.behance.net",
    category: "디자인/UX",
    subcategory: "디자인 레퍼런스",
    summary: "Adobe의 크리에이티브 포트폴리오 플랫폼. UX/UI·그래픽·브랜딩 디자인 트렌드 발굴",
    tags: ["UI","레퍼런스","디자인"],
    tone: "#1769ff",
  },
  {
    name: "getdesign.md",
    url: "https://getdesign.md",
    category: "디자인/UX",
    subcategory: "디자인 레퍼런스",
    summary: "해외 우수 사이트 디자인 트렌드 & 영감 큐레이션. UX/UI 레퍼런스 모음",
    tags: ["UI","레퍼런스","디자인"],
    tone: "#6366f1",
  },
  {
    name: "Freepik",
    url: "https://www.freepik.com",
    category: "디자인/UX",
    subcategory: "아이콘/에셋",
    summary: "스톡 이미지·벡터·PSD·템플릿 최대 플랫폼. AI 생성 이미지 검색 및 무료 리소스 제공",
    tags: ["에셋","이미지","리소스"],
    tone: "#00a680",
  },
  {
    name: "Pexels",
    url: "https://www.pexels.com",
    category: "디자인/UX",
    subcategory: "아이콘/에셋",
    summary: "무료 사진·영상 스톡. 저작권 걱정 없이 상업적 사용 가능한 고품질 미디어",
    tags: ["에셋","이미지","리소스"],
    tone: "#05a081",
  },
  {
    name: "Flaticon",
    url: "https://www.flaticon.com",
    category: "디자인/UX",
    subcategory: "아이콘/에셋",
    summary: "Freepik 계열 아이콘 전문 사이트. 900만개+ 무료 아이콘 PNG·SVG·폰트 제공",
    tags: ["에셋","이미지","리소스"],
    tone: "#00c4f4",
  },
  {
    name: "Udio",
    url: "https://www.udio.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "고품질 AI 음악 생성 플랫폼. 다양한 장르 & 세밀한 스타일 컨트롤",
    tags: ["음악","오디오","생성"],
    tone: "#6366f1",
  },
  {
    name: "AIVA",
    url: "https://www.aiva.ai",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "영화·게임·광고용 AI 음악 작곡. 클래식·오케스트라 스타일 특화",
    tags: ["음악","오디오","생성"],
    tone: "#c026d3",
  },
  {
    name: "Soundraw",
    url: "https://soundraw.io",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "저작권 걱정 없는 AI 음악 생성. 영상·팟캐스트·광고용 배경음악 최적",
    tags: ["음악","오디오","생성"],
    tone: "#10b981",
  },
  {
    name: "Mubert",
    url: "https://mubert.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "AI 음악 스트리밍 & 생성 서비스. 무드·템포 설정으로 맞춤 음악 생성",
    tags: ["음악","오디오","생성"],
    tone: "#10b981",
  },
  {
    name: "Boomy",
    url: "https://boomy.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "몇 초 만에 AI 음악을 만들고 스트리밍 플랫폼에 배포하는 서비스",
    tags: ["음악","오디오","생성"],
    tone: "#f59e0b",
  },
  {
    name: "Murf",
    url: "https://murf.ai",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "전문가용 AI 보이스오버 플랫폼. 200개+ 목소리, 영상·팟캐스트 더빙 최적",
    tags: ["음성","TTS","더빙"],
    tone: "#6366f1",
  },
  {
    name: "HeyGen",
    url: "https://www.heygen.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "AI 아바타 & 다국어 음성 더빙 비디오 생성. 영상 번역·현지화 특화",
    tags: ["음성","TTS","더빙"],
    tone: "#ec4899",
  },
  {
    name: "Descript",
    url: "https://www.descript.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "텍스트로 편집하는 AI 팟캐스트 & 비디오 도구. Over-Dub 음성 복제 기능",
    tags: ["음성","TTS","더빙"],
    tone: "#10b981",
  },
  {
    name: "Whisper",
    url: "https://openai.com/research/whisper",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "OpenAI 오픈소스 음성 인식(STT) 모델. 99개 언어 지원, 정확도 최상급",
    tags: ["음성","TTS","더빙"],
    tone: "#374151",
  },
  {
    name: "Speechify",
    url: "https://speechify.com",
    category: "음성/음악",
    subcategory: "음악/음성",
    summary: "AI TTS 독서 앱. 어떤 텍스트든 자연스러운 음성으로 읽어주는 앱",
    tags: ["음성","TTS","더빙"],
    tone: "#0ea5e9",
  },
  {
    name: "GitHub Copilot",
    url: "https://github.com/features/copilot",
    category: "개발/코딩",
    subcategory: "AI 코드 에디터",
    summary: "GitHub & OpenAI의 AI 페어 프로그래밍. 모든 주요 IDE 플러그인 지원",
    tags: ["코딩","개발","AI"],
    tone: "#374151",
  },
  {
    name: "Codeium",
    url: "https://codeium.com",
    category: "개발/코딩",
    subcategory: "AI 코드 에디터",
    summary: "무료 AI 코드 자동완성. 70개+ 언어, 40개+ IDE 지원, 무제한 무료",
    tags: ["코딩","개발","AI"],
    tone: "#10b981",
  },
  {
    name: "Bolt.new",
    url: "https://bolt.new",
    category: "개발/코딩",
    subcategory: "앱/웹 빌더",
    summary: "StackBlitz AI 풀스택 웹앱 빌더. 브라우저에서 즉시 실행 & 배포 가능",
    tags: ["웹앱","빌더","개발"],
    tone: "#7c3aed",
  },
  {
    name: "요즘IT",
    url: "https://yozm.wishket.com/magazine",
    category: "개발/코딩",
    subcategory: "개발자 커뮤니티",
    summary: "Wishket이 운영하는 국내 IT 개발자 매거진. 트렌드·실무·커리어 아티클 큐레이션",
    tags: ["개발자","뉴스","커뮤니티"],
    tone: "#2563eb",
  },
  {
    name: "GeekNews",
    url: "https://news.hada.io",
    category: "개발/코딩",
    subcategory: "개발자 커뮤니티",
    summary: "한국판 Hacker News. 개발자 기술 뉴스·오픈소스·AI 소식 큐레이션",
    tags: ["개발자","뉴스","커뮤니티"],
    tone: "#374151",
  },
  {
    name: "Medium",
    url: "https://medium.com",
    category: "개발/코딩",
    subcategory: "개발자 커뮤니티",
    summary: "글로벌 기술 블로그 플랫폼. AI·개발·스타트업 심층 아티클 풍부",
    tags: ["개발자","뉴스","커뮤니티"],
    tone: "#1a1a1a",
  },
  {
    name: "Fal.ai",
    url: "https://fal.ai",
    category: "개발/코딩",
    subcategory: "앱/웹 빌더",
    summary: "이미지·비디오 생성 모델 서버리스 고속 추론 플랫폼. Flux·LoRA 등 최신 모델 즉시 실행 API",
    tags: ["웹앱","빌더","개발"],
    tone: "#22c55e",
  },
  {
    name: "Jasper AI",
    url: "https://www.jasper.ai",
    category: "생산성",
    subcategory: "AI 글쓰기",
    summary: "마케팅 팀을 위한 AI 콘텐츠 작성. SEO 블로그·광고·이메일 자동 생성",
    tags: ["글쓰기","마케팅","콘텐츠"],
    tone: "#f59e0b",
  },
  {
    name: "Copy.ai",
    url: "https://www.copy.ai",
    category: "생산성",
    subcategory: "AI 글쓰기",
    summary: "AI 카피라이팅 & 마케팅 문구 생성. 90개+ 템플릿, 팀 협업 워크플로우",
    tags: ["글쓰기","마케팅","콘텐츠"],
    tone: "#6366f1",
  },
  {
    name: "Grammarly",
    url: "https://www.grammarly.com",
    category: "생산성",
    subcategory: "AI 글쓰기",
    summary: "AI 영어 문법 교정 & 글쓰기 보조. 어조 조절·표절 검사·스타일 개선",
    tags: ["글쓰기","마케팅","콘텐츠"],
    tone: "#15c39a",
  },
  {
    name: "Writesonic",
    url: "https://writesonic.com",
    category: "생산성",
    subcategory: "AI 글쓰기",
    summary: "SEO 특화 AI 글쓰기 도구. 블로그·광고·랜딩페이지 콘텐츠 자동 생성",
    tags: ["글쓰기","마케팅","콘텐츠"],
    tone: "#8b5cf6",
  },
  {
    name: "Rytr",
    url: "https://rytr.me",
    category: "생산성",
    subcategory: "AI 글쓰기",
    summary: "40개+ 언어, 40개+ 유스케이스 지원 AI 글쓰기. 가성비 최고 AI 작문 도구",
    tags: ["글쓰기","마케팅","콘텐츠"],
    tone: "#0ea5e9",
  },
  {
    name: "Gamma",
    url: "https://gamma.app",
    category: "생산성",
    subcategory: "프레젠테이션",
    summary: "텍스트 입력만으로 아름다운 프레젠테이션 자동 생성. PPT·문서·웹페이지 변환",
    tags: ["프레젠테이션","슬라이드","문서"],
    tone: "#6366f1",
  },
  {
    name: "Tome",
    url: "https://tome.app",
    category: "생산성",
    subcategory: "프레젠테이션",
    summary: "AI 스토리텔링 & 프레젠테이션 도구. 내러티브 중심 슬라이드 자동 구성",
    tags: ["프레젠테이션","슬라이드","문서"],
    tone: "#7c3aed",
  },
  {
    name: "Beautiful.ai",
    url: "https://www.beautiful.ai",
    category: "생산성",
    subcategory: "프레젠테이션",
    summary: "AI 스마트 슬라이드 레이아웃 자동 조정. 디자인 지식 없이 전문가 PPT 제작",
    tags: ["프레젠테이션","슬라이드","문서"],
    tone: "#ec4899",
  },
  {
    name: "Plus AI",
    url: "https://www.plusdocs.com",
    category: "생산성",
    subcategory: "프레젠테이션",
    summary: "Google Slides·PowerPoint용 AI 플러그인. 기존 도구에서 바로 AI 프레젠테이션",
    tags: ["프레젠테이션","슬라이드","문서"],
    tone: "#0ea5e9",
  },
  {
    name: "Taskade",
    url: "https://www.taskade.com",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "AI 기반 프로젝트 관리 & 팀 협업. AI 에이전트로 업무 자동화",
    tags: ["생산성","업무","요약"],
    tone: "#10b981",
  },
  {
    name: "Otter.ai",
    url: "https://otter.ai",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "실시간 AI 회의 자동 녹취·요약·번역. Zoom·Teams·Google Meet 통합",
    tags: ["생산성","업무","요약"],
    tone: "#6366f1",
  },
  {
    name: "Mem.ai",
    url: "https://mem.ai",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "AI 자동 정리 노트 앱. 내용 간 연결 & 검색, AI 요약 자동 생성",
    tags: ["생산성","업무","요약"],
    tone: "#ec4899",
  },
  {
    name: "NotebookLM",
    url: "https://notebooklm.google.com",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "Google의 AI 노트북. 문서·PDF 업로드 후 AI 질답·요약·팟캐스트 자동 생성",
    tags: ["생산성","업무","요약"],
    tone: "#4285f4",
  },
  {
    name: "Julius AI",
    url: "https://julius.ai",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "AI 데이터 분석 노트북. CSV·Excel 업로드 후 차트·통계·인사이트 자동 생성",
    tags: ["생산성","업무","요약"],
    tone: "#f97316",
  },
  {
    name: "Elicit",
    url: "https://elicit.com",
    category: "생산성",
    subcategory: "업무 생산성",
    summary: "학술 논문 특화 AI 리서치 어시스턴트. 논문 요약·비교·근거 추출 자동화",
    tags: ["생산성","업무","요약"],
    tone: "#8b5cf6",
  },
  {
    name: "HF Papers",
    url: "https://huggingface.co/papers",
    category: "플랫폼/리서치",
    subcategory: "모델 허브",
    summary: "Hugging Face의 AI 논문 큐레이션 허브. 매일 업데이트되는 최신 AI 연구 논문 & 커뮤니티 토론",
    tags: ["모델","데이터셋","오픈소스"],
    tone: "#ff9a00",
  },
  {
    name: "Ollama",
    url: "https://ollama.com",
    category: "플랫폼/리서치",
    subcategory: "모델 허브",
    summary: "로컬 PC에서 AI 모델 실행. 완전한 프라이버시, Llama·Gemma·Mistral 지원",
    tags: ["모델","데이터셋","오픈소스"],
    tone: "#374151",
  },
  {
    name: "LM Studio",
    url: "https://lmstudio.ai",
    category: "플랫폼/리서치",
    subcategory: "모델 허브",
    summary: "로컬 LLM GUI 실행 데스크톱 앱. 설치 쉽고 직관적, 초보자 친화적",
    tags: ["모델","데이터셋","오픈소스"],
    tone: "#10b981",
  },
  {
    name: "Kaggle",
    url: "https://www.kaggle.com",
    category: "플랫폼/리서치",
    subcategory: "모델 허브",
    summary: "세계 최대 데이터 과학 & ML 경진대회 플랫폼. 데이터셋·노트북·모델 공유, 무료 GPU/TPU 제공",
    tags: ["모델","데이터셋","오픈소스"],
    tone: "#20beff",
  },
  {
    name: "OpenAI API",
    url: "https://platform.openai.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "GPT-4o·DALL-E 3·Whisper·Embeddings API. 전 세계 AI 앱 개발 표준 플랫폼",
    tags: ["API","모델","개발"],
    tone: "#10a37f",
  },
  {
    name: "Anthropic API",
    url: "https://console.anthropic.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "Claude 3.5 Sonnet/Opus/Haiku API 개발자 콘솔. 안전하고 강력한 AI API",
    tags: ["API","모델","개발"],
    tone: "#c2561a",
  },
  {
    name: "Groq",
    url: "https://groq.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "LPU 기반 초고속 AI 추론 API. 무료 티어 제공, Llama·Mixtral·Gemma 지원",
    tags: ["API","모델","개발"],
    tone: "#f97316",
  },
  {
    name: "Cohere",
    url: "https://cohere.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "기업용 AI 텍스트 처리 API. 임베딩·검색·분류 특화, RAG 파이프라인 최적",
    tags: ["API","모델","개발"],
    tone: "#d946ef",
  },
  {
    name: "Weights & Biases",
    url: "https://wandb.ai",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "ML 실험 추적 & 모델 관리 플랫폼. AI 프로젝트 버저닝·시각화·협업",
    tags: ["API","모델","개발"],
    tone: "#ffbe00",
  },
  {
    name: "Scale AI",
    url: "https://scale.com",
    category: "개발/코딩",
    subcategory: "AI 개발 플랫폼",
    summary: "AI 학습 데이터 레이블링 & 평가 플랫폼. AI 모델 품질 향상의 핵심 도구",
    tags: ["API","모델","개발"],
    tone: "#ff6b35",
  },
  {
    name: "Coursera",
    url: "https://www.coursera.org",
    category: "교육/학습",
    subcategory: "온라인 강의",
    summary: "세계 최대 온라인 교육 플랫폼. Stanford·Google·IBM 등 명문대·기업 강의 7,000개+",
    tags: ["강의","학습","교육"],
    tone: "#0056d2",
  },
  {
    name: "Udemy",
    url: "https://www.udemy.com",
    category: "교육/학습",
    subcategory: "온라인 강의",
    summary: "21만개+ 강좌 보유 온라인 학습 플랫폼. 실무 중심 개발·디자인·AI 기술 강의 특화",
    tags: ["강의","학습","교육"],
    tone: "#a435f0",
  },
  {
    name: "K-MOOC",
    url: "https://www.kmooc.kr",
    category: "교육/학습",
    subcategory: "온라인 강의",
    summary: "한국 국가평생교육진흥원 운영 무료 온라인 강의. 국내 주요 대학 강의 무료 수강",
    tags: ["강의","학습","교육"],
    tone: "#00a8e8",
  },
  {
    name: "DeepLearning.AI",
    url: "https://www.deeplearning.ai",
    category: "교육/학습",
    subcategory: "온라인 강의",
    summary: "Andrew Ng이 설립한 AI·ML 전문 교육 플랫폼. Coursera 연동, 딥러닝·LLM·MLOps 강의",
    tags: ["강의","학습","교육"],
    tone: "#e84118",
  },
];
